name: Build OCI Images
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'latest'

jobs:
  build:
    # Job name is oci
    name: oci
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build OCI images
        env:
          REGISTRY: ""
          VERSION: "${{ github.event.inputs.version }}"
          OUT_DIR: ${{ github.event.inputs.home }}/out
        run: cd ${{ github.event.inputs.home }}/norma/images && source build.sh
